spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diploma?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    dialect:
      org:
        hibernate:
          dialect: MySQL8Dialect
    show-sql: true
---
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@mail.ru
copyright: Дмитрий Сергеев
copyrightFrom: 2005
---
MULTIUSER_MODE: false
POST_PREMODERATION: false
STATISTICS_IS_PUBLIC: false

---
flyway:
  user: root
  password: password
  schemas: diploma
  url: jdbc:mysql://localhost:3306/diploma?useSSL=false&serverTimezone=UTC
  locations: filesystem:db/migration

