spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diploma?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
---
title: DevPub
subtitle: Рассказы разработчиков
phone: +7 903 666-44-55
email: mail@mail.ru
copyright: Дмитрий Сергеев
copyrightFrom: 2005
